---
- name: Add NVIDIA CTK repo
  ansible.builtin.deb822_repository:
    name: nvidia-ctk
    types: deb
    uris: https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)
    suites: '/'
    signed_by: https://nvidia.github.io/libnvidia-container/gpgkey

- name: Install NVIDIA Docker Container Toolkit base
  ansible.builtin.apt:
    package: nvidia-container-toolkit
    state: present
    update_cache: true
  notify: Reboot system
