---
- name: Include Nvidia install tasks
  ansible.builtin.include_tasks:
    file: "install_{{ ansible_os_family }}.yml"

- name: Copy over Docker daemon config
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    group: root
    owner: root
    mode: "0644"
  notify: Restart docker

- name: Copy over Nvidia CDI regeneration udev rule
  ansible.builtin.copy:
    src: files/70-nvidia-ctk.rules
    dest: /lib/udev/rules.d/70-nvidia-ctk.rules
    group: root
    owner: root
    mode: "0644"
