# Base directory where to configure Docker
docker_base_dir: "/srv/docker"
# Directory for compose projects
docker_compose_dir: "/srv/docker/compose"
# Directory for volume data
docker_data_dir: "/srv/docker/data"
# Whether or not to enable backups
docker_configure_backups: false
# Restic backup repository location
docker_restic_repository: "/srv/docker/backups"
