- name: Install Samba packages
  ansible.builtin.package:
    name: samba
    state: present

- name: Template Samba config
  ansible.builtin.template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart Samba

- name: Start SMB service
  ansible.builtin.service:
    name: smb
    state: started
    enabled: true

- name: Start NMB service
  ansible.builtin.service:
    name: nmb
    state: started
    enabled: true
