---
- name: Install ZFS from backports
  ansible.builtin.apt:
      name: zfsutils-linux
      state: present
      default_release: "{{ ansible_facts['distribution_release'] }}-backports"
  notify: Reboot system
