# Default set of templates to configure for Alloy, good for 99 percent of systems.
alloy_templates:
  - { src: 'templates/config.alloy.arcs.j2', dest: '/etc/alloy/arcs.alloy' }

# Server implementing Alloy Remote Config API
alloy_arcs_url: "http://example.com"

# Comma separated string: templates to request from the ARCS server
alloy_arcs_templates: "default"
