---
- name: Remove old Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
    autoremove: true

- name: Install required packages for GPG key
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0444"

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ __docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_lsb.id | lower }}   {{ ansible_lsb.codename }} stable"  # noqa yaml[line-length]
    filename: docker

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
