- name: Install systemd-resolved
  ansible.builtin.package:
      name: systemd-resolved
      state: present
  notify: Reboot system

- name: Enable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true
