- name: Populate service facts
  ansible.builtin.service_facts:

- name: Enable fstrim timer
  ansible.builtin.service:
    name: fstrim.timer
    enabled: true

- name: Enable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true

- name: Set timezone
  community.general.timezone:
    name: America/New_York

- name: Check if netplan is installed
  ansible.builtin.stat:
    path: /usr/sbin/netplan
  register: base_netplan_check

- name: Reconfigure netplan to use NetworkManager
  when:
    - ansible_distribution == "Ubuntu"
    - base_netplan_check.stat.exists
  block:
    - name: Install NetworkManager
      ansible.builtin.package:
        name: network-manager
        state: present

    - name: Remove cloud-init netplan configuration
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
      notify: Reboot system

    - name: Create netplan configuration
      ansible.builtin.copy:
        content: |
          network:
            version: 2
            renderer: NetworkManager
        dest: /etc/netplan/01-network-manager.yaml
        owner: root
        group: root
        mode: '0644'
      notify: Reboot system

    - name: Apply netplan configuration # noqa no-changed-when
      ansible.builtin.command: netplan apply

    - name: Stop/disable/mask systemd-networkd service
      ansible.builtin.systemd_service:
        name: systemd-networkd.service
        state: stopped
        enabled: false
        masked: true
      failed_when: false
      notify: Reboot system

    - name: Stop/disable/mask systemd-networkd.socket service
      ansible.builtin.systemd_service:
        name: systemd-networkd.socket
        state: stopped
        enabled: false
        masked: true
      failed_when: false
      notify: Reboot system

    - name: Stop/disable/mask systemd-networkd-wait-online service
      ansible.builtin.systemd_service:
        name: systemd-networkd-wait-online.service
        state: stopped
        enabled: false
        masked: true
      failed_when: false
      notify: Reboot system
